name: Deploy Cloud Run Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      uses: docker/setup-docker@v1

    - name: Build and push Docker image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        IMAGE_NAME: my-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} .
        docker push gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG}

    - name: Initialize Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@v2
      with:
        args: plan -var="image=gcr.io/${{ secrets.PROJECT_ID }}/my-image:${{ github.sha }}"

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@v2
      with:
        args: apply -auto-approve -var="image=gcr.io/${{ secrets.PROJECT_ID }}/my-image:${{ github.sha }}"
